n

diff --git a/scripts/sh/cd-add/cd-add b/scripts/sh/cd-add/cd-add
--- a/scripts/sh/cd-add/cd-add
+++ b/scripts/sh/cd-add/cd-add
@@ -1,47 +1,56 @@
 #!/bin/sh
 
+# > cd-add .dotfiles
+# This is the executed command: echo /home/wurfkreuz//home/wurfkreuz/.dotfiles >> /home/wurfkreuz/.dirs
+
+# Secondly, i need to check if the added path exists.
+
+dirs_path=""
+
 clean_file() {
     temp_file=$(mktemp) || exit 1
-    dir_file="$HOME/.dirs"
+    dir_file="$HOME/.dotfiles/scripts/sh/cd-add/.dirs"
     # NF is 'number of fields'. Don't forget that field in awk is a symbol
     # separated by whitespaces.
     awk 'NF > 0' "$dir_file" | sort -d | uniq > "$temp_file"
-    rm "$dir_file"
     mv "$temp_file" "$dir_file"
 }
 
 main() {
-    if [ ! -e "$HOME"/.dirs ]; then
-		echo "Can't symlink the \"~/.dotfiles/scripts/sh/cd-add/.dirs\". You already have a file or directory with the name '.dirs'."
+	# The -h flag is for cheking symlinks (the man page says about the -l flag also, but it doesn't work)
+    if [ -e "$HOME"/.dirs ] && [ ! -h "$HOME"/.dirs ]; then
+		echo "Can't symlink the \"~/.dotfiles/scripts/sh/cd-add/.dirs\". You already have a file or directory with the name '.dirs'."; exit 1;
     elif [ ! -e "$HOME"/.dirs ]; then
-        ln -s "$HOME"/.dotfiles/scripts/sh/cd-add/.dirs "$HOME"
+        ln -s "$HOME/.dotfiles/scripts/sh/cd-add/.dirs" "$HOME"
     fi
 
     clean_file
-    current_path="$1"
     # If i don't give any parameter
     if [ -z "$1" ]; then
-        current_path=$(pwd)
-        echo "$current_path" >> "$HOME"/.dirs
-		echo "This is the executed command: echo $current_path >> $HOME/.dirs"
-        echo "$current_path is added."
-        # If i write a full path for some reason with '/home...' or "~/", then i
-        # just insert the given path.
-    elif [ "$(echo "$1" | cut -c -5)" = "/home" ]; then
+        dirs_path=$(pwd)
         echo "$1" >> "$HOME"/.dirs
 		echo "This is the executed command: echo $1 >> $HOME/.dirs"
         echo "$1 is added."
-        # If the given parameter doesn't exist and the logic implies, that i just
-        # gave an unfull path
-    elif [ ! -f "$current_path" ]; then
-        current_path="$(pwd)/$current_path"
-        echo "$(pwd)/$current_path" >> "$HOME"/.dirs
-		echo "This is the executed command: echo $(pwd)/$current_path >> $HOME/.dirs"
-        echo "$(pwd)/$current_path is added."
+    # If i write a full path for some reason with '/home...' or "~/", then i
+    # just insert the given path.
+    elif [ "$(echo "$1" | cut -c -5)" = "/home" ]; then
+		dirs_path="$1"
+		[ -d "$dirs_path" ] || { echo "Path $dirs_path doesn't exist."; exit 1; }
+        echo "$1" >> "$HOME"/.dirs
+		echo "This is the executed command: echo $1 >> $HOME/.dirs"
+        echo "$1 is added."
+    # If the given parameter doesn't exist and the logic implies, that i just
+    # gave an unfull path
+    elif [ ! -f "$1" ]; then
+        dirs_path="$(pwd)/$1"
+		[ -d "$dirs_path" ] || { echo "Path $dirs_path doesn't exist."; exit 1; }
+        echo "$(pwd)/$1" >> "$HOME"/.dirs
+		echo "This is the executed command: echo $(pwd)/$1 >> $HOME/.dirs"
+        echo "$(pwd)/$1 is added."
     else
-        echo "$current_path" >> "$HOME"/.dirs 
-		echo "This is the executed command: echo $current_path >> $HOME/.dirs"
-        echo "$current_path is added."
+        echo "$1" >> "$HOME"/.dirs 
+		echo "This is the executed command: echo $1 >> $HOME/.dirs"
+        echo "$1 is added."
     fi
 }
 
